# Generated by Django 4.2.4 on 2023-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderplaced_status_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='Benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AL', 'Almonds'), ('PI', 'Pistachios'), ('CA', 'Cashew'), ('AP', 'Apricot'), ('DA', 'Dates'), ('HA', 'Hazelnuts'), ('PE', 'Peanut'), ('BN', 'Betel-Nut'), ('DC', 'Dry-Coconut'), ('WL', 'Walnuts'), ('RA', 'Raisins'), ('SE', 'Seeds'), ('PR', 'Prunes'), ('DF', 'Dry-Figs'), ('FN', 'Fox-Nuts'), ('DB', 'Dry-Berries'), ('PE', 'Pecans'), ('CN', 'Corn-Nuts')], max_length=2),
        ),
    ]
