# Generated by Django 4.2.4 on 2023-09-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_benefits_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='benefits',
            new_name='benefit',
        ),
    ]
