# Generated by Django 4.2.4 on 2023-09-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_benefits_product_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='benefit',
            new_name='benefits',
        ),
    ]
